#!/bin/sh

uci -q batch <<-EOF >/dev/null
  delete network.vpn
  set network.vpn=interface
  set network.vpn.proto=none
  set network.vpn.ifname=ppp+
  set network.vpn.auto=1
  commit network
EOF

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@pptpd[-1]
	add ucitrack pptpd
	set ucitrack.@pptpd[-1].init=pptpd
	commit ucitrack
EOF

/etc/init.d/pptpd enable && /etc/init.d/pptpd restart

rm -f /tmp/luci-indexcache
exit 0
