#!/bin/sh /etc/rc.common
# Copyright (C) 2015 OpenWrt.org

START=60
USE_PROCD=1

BIN=/usr/sbin/pptpd
CONFIG=/var/etc/pptpd.conf
CHAP_SECRETS=/var/etc/chap-secrets
OPTIONS_PPTP=/var/etc/options.pptpd

validate_login_section() {
	uci_validate_section pptpd login "${1}" \
		'username:string' \
		'password:string'
}

validate_pptpd_section() {
	uci_validate_section pptpd service "${1}" \
		'enabled:uinteger' \
		'localip:string' \
		'remoteip:string' \
		'mppe:list(string):required no40 no56 stateless' \
		'logwtmp:uinteger'
}

setup_login() {
	validate_login_section "${1}" || {
		echo "validation failed"
		return 1
	}

	[ -n "${username}" ] || return 0
	[ -n "${password}" ] || return 0

	echo "${username} pptp-server ${password} *" >> $CHAP_SECRETS
}

setup_config() {
	local enabled localip remoteip mppe

	validate_pptpd_section "${1}" || {
		echo "validation failed"
		return 1
	}

	[ "$enabled" -eq 0 ] && {
		if [ "$(uci get firewall.vpn 2>/dev/null)" = "zone" ]; then
			uci -q batch <<-EOF >/dev/null
  delete firewall.vpn
  delete firewall.vpn2lan
  delete firewall.vpn2wan
  delete firewall.lan2vpn
  delete firewall.pptp
  delete firewall.gre
  commit firewall
EOF
			service firewall reload
		fi
		return 1
	}

	if [ -z "$(uci get firewall.vpn 2>/dev/null)" ]; then
		uci -q batch <<-EOF >/dev/null
  set firewall.vpn=zone
  set firewall.vpn.name=vpn
  set firewall.vpn.network=vpn
  set firewall.vpn.input=ACCEPT
  set firewall.vpn.forward=REJECT
  set firewall.vpn.output=ACCEPT
  add firewall forwarding
  rename firewall.@forwarding[-1]="vpn2lan"
  set firewall.@forwarding[-1].src="vpn"
  set firewall.@forwarding[-1].dest="lan"
  add firewall forwarding
  rename firewall.@forwarding[-1]="vpn2wan"
  set firewall.@forwarding[-1].src="vpn"
  set firewall.@forwarding[-1].dest="wan"
  add firewall forwarding
  rename firewall.@forwarding[-1]="lan2vpn"
  set firewall.@forwarding[-1].src="lan"
  set firewall.@forwarding[-1].dest="vpn"
  add firewall rule 
  rename firewall.@rule[-1]="pptp"
  set firewall.@rule[-1].name="pptp"
  set firewall.@rule[-1].target="ACCEPT"
  set firewall.@rule[-1].src="wan"
  set firewall.@rule[-1].proto="tcp"
  set firewall.@rule[-1].dest_port="1723"
  add firewall rule 
  rename firewall.@rule[-1]="gre"
  set firewall.@rule[-1].name="gre"
  set firewall.@rule[-1].target="ACCEPT"
  set firewall.@rule[-1].src="wan"
  set firewall.@rule[-1].proto="47"
  commit firewall
EOF
		service firewall reload
	fi

	mkdir -p /var/etc
	cp /etc/pptpd.conf $CONFIG
	cp /etc/ppp/options.pptpd $OPTIONS_PPTP

	[ -n "$localip" ] && echo "localip  $localip" >> $CONFIG
	[ -n "$remoteip" ] && echo "remoteip  $remoteip" >> $CONFIG
	[ "$logwtmp" -eq 1 ] && echo "logwtmp" >> $CONFIG

	echo "mppe $(echo $mppe | sed -e 's/\s/,/g')" >> $OPTIONS_PPTP

	return 0
}

start_service() {
	config_load pptpd
	setup_config pptpd || return
	config_foreach setup_login login

	ln -sfn $CHAP_SECRETS /etc/ppp/chap-secrets

	procd_open_instance
	procd_set_param command $BIN -c $CONFIG --fg -o $OPTIONS_PPTP
	procd_close_instance
}
