#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@dnscrypt-proxy-2[-1]
	add ucitrack dnscrypt-proxy-2
	set ucitrack.@dnscrypt-proxy-2[-1].init=dnscrypt-proxy-2
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
